apiVersion: v1
kind: ConfigMap
metadata:
  name: buildah-registries-conf
  namespace: skala-practice
  labels:
    app: new-jenkins
    component: buildah-config
data:
  registries.conf: |
    unqualified-search-registries = ["docker.io","quay.io","registry.fedoraproject.org"]

  containers.conf: |
    [network]
    network_backend = "cni"