IMAGE_NAME="myfirst-api-server"
VERSION="1.0.0-kaniko"

DOCKER_REGISTRY="amdp-registry.skala-ai.com/skala25a"
DOCKER_REGISTRY_USER='robot$skala25a'
DOCKER_REGISTRY_PASSWORD="1qB9cyusbNComZPHAdjNIFWinf52xaBJ"
