apiVersion: v1
kind: Secret
metadata:
  name: sk067-git-repo
  namespace: skala-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: sk067-my-app
  type: git
  url: https://github.com/hangyu3581/myfirst-api-server/tree/main/10.myfirst-api-server
  username: hangyu3581
  project: skala
  password: ${GITHUB_PAT}
